# Basic Settings
host: 0.0.0.0
port: 80
ssl_port: 443
webdir: C:\www
enable_ssl: false

# SSL Settings
ssl_redirect: true
ssl_redirect_path: https://yourdomain.com/$1
cert_path: server.pem
key_path: key.pem

# Advanced Settings
minify: true
natura_lang: true